server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        platform: h2
        url: jdbc:h2:mem:oauth;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
